"""Generate hoard_link/ui/hoard-theme.css: the shared Hoard look (the one
Writer's Hoard has) with one palette per app.

Every palette is the same charcoal ladder tinted toward the app's own hue
(the colour of its dragon icon) plus that hue as the accent. Run (from the HoardLink repo):

    python scripts/hoard_palettes.py > hoard_link/ui/hoard-theme.css
"""
from __future__ import annotations

import colorsys

# id: (accent hex, base-tint hue or None for the accent's hue, tint saturation)
PALETTES: dict[str, tuple[str, float | None, float]] = {
    "writer":       ("#d5b575", 190, 0.05),
    "hub":          ("#e2b24c", None, 0.16),
    "argus":        ("#8f84f4", None, 0.192),
    "babel":        ("#bd78e6", None, 0.192),
    "borges":       ("#d9665d", None, 0.16),
    "cassandra":    ("#e466a0", None, 0.176),
    "cicero":       ("#d98f86", None, 0.144),
    "daguerre":     ("#45bccb", None, 0.176),
    "diskhoard":    ("#45c58f", None, 0.16),
    "dorian":       ("#df5b74", None, 0.176),
    "echo":         ("#a77de4", None, 0.192),
    "funes":        ("#b9c1cd", 215, 0.10),
    "gepetto":      ("#d58448", None, 0.16),
    "homehoard":    ("#e5913f", None, 0.16),
    "hypatia":      ("#50c67e", None, 0.16),
    "jobhunter":    ("#e8a83c", None, 0.16),
    "kafka":        ("#a8aa5c", None, 0.16),
    "laplace":      ("#97c854", None, 0.16),
    "ledger":       ("#cfa660", None, 0.144),
    "links":        ("#76a3d2", None, 0.192),
    "lumiere":      ("#de6fe8", None, 0.176),
    "mercator":     ("#36bbdb", None, 0.192),
    "midas":        ("#e0bd4b", None, 0.16),
    "nightingale":  ("#de8396", None, 0.16),
    "people":       ("#d6905f", None, 0.16),
    "phileas":      ("#3fbfae", None, 0.16),
    "platos":       ("#8378e8", None, 0.192),
    "prospero":     ("#e65db6", None, 0.192),
    "scheherazade": ("#6c82ec", None, 0.22),
    "tantalus":     ("#ec8a40", None, 0.16),
    "vitruvius":    ("#6a8ced", None, 0.208),
    "vulcan":       ("#e66d40", None, 0.16),
}


def hx(h: float, s: float, l: float) -> str:
    r, g, b = colorsys.hls_to_rgb((h % 360) / 360, l, s)
    return "#%02x%02x%02x" % (round(r * 255), round(g * 255), round(b * 255))


def rgb(c: str) -> tuple[float, float, float]:
    return tuple(int(c[i:i + 2], 16) / 255 for i in (1, 3, 5))  # type: ignore[return-value]


def lum(c: str) -> float:
    def ch(v: float) -> float:
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
    r, g, b = rgb(c)
    return 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b)


def contrast(a: str, b: str) -> float:
    la, lb = sorted((lum(a), lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def hue_of(c: str) -> float:
    h, _l, _s = colorsys.rgb_to_hls(*rgb(c))
    return h * 360


def palette(accent: str, tint_hue: float | None, sat: float) -> dict[str, str]:
    h = hue_of(accent) if tint_hue is None else tint_hue
    deep = hx(h, sat, 0.095)
    p = {
        "deep": deep,
        "sunken": hx(h, sat, 0.075),
        "surface": hx(h, sat * 0.9, 0.125),
        "elevated": hx(h, sat * 0.8, 0.165),
        "hover": hx(h, sat * 0.8, 0.195),
        "border": hx(h, sat * 0.7, 0.235),
        "border-hover": hx(h, sat * 0.6, 0.38),
        "text": hx(h, 0.22, 0.905),
        "text-muted": hx(h, 0.07, 0.725),
        "text-dim": hx(h, 0.06, 0.63),
        "accent": accent,
    }
    ah, al, as_ = colorsys.rgb_to_hls(*rgb(accent))
    p["accent-strong"] = hx(ah * 360, as_, min(0.85, al + 0.08))
    p["accent-dim"] = hx(ah * 360, as_ * 0.8, max(0.3, al - 0.12))
    dark_ink = hx(h, sat, 0.09)
    p["accent-ink"] = dark_ink if contrast(accent, dark_ink) >= 4.5 else "#ffffff"
    return p


HEADER = '''/* Hoard theme — the shared look of the Hoard family (the one Writer's
   Hoard has): charcoal surfaces, serif display type, one accent per app.
   GENERATED by scripts/hoard_palettes.py — edit the table there, not this
   file. Vendored byte-identical into every app (scripts/sync_theme.py).

   Use: <html data-hoard-app="<id>"> + this file before the app's own CSS;
   the app maps its variables onto --hoard-*. Without data-hoard-app the
   Writer's palette applies. */

:root {
  color-scheme: dark;
  --hoard-font-serif: 'Cinzel', 'Iowan Old Style', Charter, Georgia, 'Liberation Serif', 'Noto Serif', 'Times New Roman', serif;
  --hoard-font-sans: 'Source Sans 3', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans', 'Liberation Sans', Arial, sans-serif;
  --hoard-font-mono: 'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace;
  --hoard-radius-sm: 6px;
  --hoard-radius: 8px;
  --hoard-radius-lg: 10px;
  --hoard-sidebar-w: 220px;
  --hoard-header-h: 64px;
  --hoard-success: #4a9e6d;
  --hoard-warning: #d4a843;
  --hoard-danger: #c4463a;
  --hoard-info: #4a7ec4;
  --hoard-shadow: 0 8px 28px rgba(0, 0, 0, 0.38);
  --hoard-focus: 0 0 0 2px var(--hoard-accent);
}
'''

BASE = '''
/* ── Base ─────────────────────────────────────────────────────────────── */
html { background: var(--hoard-deep); }
body {
  background: var(--hoard-deep);
  color: var(--hoard-text);
  font-family: var(--hoard-font-sans);
  -webkit-font-smoothing: antialiased;
}
::selection { background: var(--hoard-accent-soft); color: var(--hoard-text); }
:focus-visible { outline: 2px solid var(--hoard-accent); outline-offset: 2px; }
* { scrollbar-width: thin; scrollbar-color: var(--hoard-border) transparent; }
::-webkit-scrollbar { width: 10px; height: 10px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: var(--hoard-border); border-radius: 8px; border: 2px solid var(--hoard-deep); }
::-webkit-scrollbar-thumb:hover { background: var(--hoard-border-hover); }
::-webkit-scrollbar-corner { background: transparent; }

/* ── Opt-in building blocks (class names only these files use) ───────── */
.hoard-brand {
  font-family: var(--hoard-font-serif);
  font-weight: 700;
  color: var(--hoard-accent);
  letter-spacing: 0.01em;
}
.hoard-display { font-family: var(--hoard-font-serif); font-weight: 700; color: var(--hoard-text); letter-spacing: 0.005em; }
.hoard-card {
  background: var(--hoard-surface);
  border: 1px solid var(--hoard-border);
  border-radius: var(--hoard-radius-lg);
}
.hoard-btn {
  display: inline-flex; align-items: center; gap: 8px;
  height: 36px; padding: 0 14px; border-radius: var(--hoard-radius);
  border: 1px solid var(--hoard-border); background: transparent; color: var(--hoard-text);
  font: 500 14px/1 var(--hoard-font-sans); cursor: pointer;
}
.hoard-btn:hover { border-color: var(--hoard-border-hover); background: var(--hoard-elevated); }
.hoard-btn-primary { background: var(--hoard-accent); border-color: var(--hoard-accent); color: var(--hoard-accent-ink); font-weight: 600; }
.hoard-btn-primary:hover { background: var(--hoard-accent-strong); border-color: var(--hoard-accent-strong); }
'''


def block(sel: str, p: dict[str, str]) -> str:
    lines = [f"{sel} {{"]
    for k, v in p.items():
        lines.append(f"  --hoard-{k}: {v};")
    r, g, b = (round(x * 255) for x in rgb(p["accent"]))
    lines.append(f"  --hoard-accent-rgb: {r}, {g}, {b};")
    lines.append(f"  --hoard-accent-soft: rgba({r}, {g}, {b}, 0.14);")
    lines.append(f"  --hoard-accent-line: rgba({r}, {g}, {b}, 0.38);")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    out = [HEADER]
    w = palette(*PALETTES["writer"])
    out.append(block(":root", w))
    for app_id, spec in PALETTES.items():
        out.append(block(f'html[data-hoard-app="{app_id}"]', palette(*spec)))
    out.append(BASE)
    print("\n\n".join(out))


if __name__ == "__main__":
    main()
